Repository solop-develop/proxy-adempiere-api, pull requests merged in 2023-06, with the labels that each got.

#155 Fix: Support to Service Process (Payment Allocation)
  package.json
  src/modules/adempiere-api/api/extensions/adempiere/form/addons/payment-allocation.ts
  yarn.lock
Labels: enhancement

#156 Update adempiere grp api to 4.4.5
  package.json
  yarn.lock
Labels: bug

#157 fix: Window chart parameter with lookup list.
  package.json
  yarn.lock
Labels: bug

#158 feat: Tree Tab with where clause.
  package.json
  src/modules/adempiere-api/api/extensions/adempiere/user-interface/component/tree.ts
  yarn.lock
Labels: enhancement

#159 fix: Set values list on filters.
  package.json
  yarn.lock
Labels: enhancement

#160 feat: List Search Info fields.
  config/default.json
  docker/adempiere-api/template.json
  package.json
  src/modules/adempiere-api/api/extensions/adempiere/dictionary/index.js
  src/modules/adempiere-api/api/extensions/adempiere/dictionary/search-info.ts
  src/modules/adempiere-api/api/extensions/adempiere/util/dictionaryFromGRPC.js
  yarn.lock
Labels: enhancement

#161 feat: Add operators restriction to `BrowseItems`.
  package.json
  yarn.lock
Labels: enhancement

#162 feat: `Criteria` filters with `ValueType`.
  package.json
  yarn.lock
Labels: bug, enhancement

#163 feat: Accouting viewer filters.
  package.json
  src/modules/adempiere-api/api/extensions/adempiere/general-ledger/index.js
  src/modules/adempiere-api/api/extensions/adempiere/general-ledger/index.ts
  src/modules/adempiere-api/api/extensions/adempiere/util/generalLedgerFromGRPC.js
  yarn.lock
Labels: enhancement
